feat: Button 컴포넌트 완료
Vallista/vallista-land pull request #2
Opened 2021-12-07 05:31 UTC by KimChunsick

feat: Button 컴포넌트 작업 완료 및 blog에서 확인 가능하게 컴포넌트 추가

Signed-off-by: deokwon <deokwon@deokwonui-MacBookPro.local>

2021-12-07 05:53 UTC, Vallista requested changes
근데 width 100% 하는 버튼일때는 어떻게 대응해요?

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +    box-shadow: ${props.variant === 'shadow' ? '0 5px 10px rgba(0,0,0,0.12)' : undefined};
props.theme.shadows 가 있음.

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +      box-shadow: ${props.variant === 'shadow' ? '0 8px 30px rgba(0,0,0,0.12)' : undefined};
props.theme.shadows 가 있음.

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +      box-shadow: ${props.variant === 'shadow' ? '0 5px 10px rgba(0,0,0,0.12)' : undefined};
props.theme.shadows 가 있음.

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +    color: ${Colors.PRIMARY.ACCENT_3};
이렇게 쓰는 거 아님.

```tsx
css`
color: ${({ theme }) => theme.colors.PRIMARY.ACCENT_3};
`
```

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +    margin-right: ${props.isPrefix ? '8px' : undefined};
```tsx
props.isPrefix && css`
margin-right: 8px; 
`
```

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +    margin-right: ${props.align === 'grow' || props.align === 'start' ? 'auto' : undefined};
undefined는 왜주십니까?

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +      width: ${props.width ? `${props.width}px` : undefined};
undefined를 왜쓰십니까?

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +  transition-property: border-color, background, color, transform, box-shadow;
transition-property가 왜 제일 위에 있습니까?

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/type.ts
> +  normal: { foreground: string; background: string; border: string }
`ThemeProvider`에 보면 `AvailablePickedColor` 가 있습니다.

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/type.ts
> +const defaultVariantColorSets = {
타입추론으로 하면 문제가 있지 않을까요?

```tsx
type ButtonColorType = 'primary' | 'secondary' | 'success' | 'error' | 'warning' | 'alert' | 'violet'
type ButtonActionType = 'nomal' | 'hover' | 'action'
type ButtonVariantColorSets = Record<ButtonColorType, Record<ButtonActionType, AvailablePickedType>>

const defaultVariantColorSets: ButtonVariantColorSets = { ... }
```

1. 왜 이렇게 하는게 더 좋을까요?
2. 이 상황은 왜 타입추론을 하면 안될까요?

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +    <Element type='submit' disabled={disabled || loading} {...otherProps} onClick={onClick}>
`submit` 은 고정인가요?

1. `'button' | 'submit' | 'reset'` 각각 지원을 해야할텐데, 왜 하지 않으셨나요?
2. sementic web을 전혀 지키지 않은 코드입니다. form과 연결하면 무조껀 button이 실행되겠군요?
3. submit은 variant와 color가 어떤 타입일 때 실행되어야 할까요? UI 적으로 생각해봅시다

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +    border: 1px solid ${props.normal?.border};
props.normal?.border 없으면 undefined.
그럼 `border: 1px solid undefined` 이므로 장애가 나겠군요..

2021-12-07 05:53 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +    color: ${props.normal?.foreground};
props.normal?.foreground 없으면 undefined.
그럼 `color: 1px solid undefined` 이므로 장애가 나겠군요..

2021-12-08 14:09 UTC, KimChunsick commented on packages/core/src/components/Button/Button.tsx
> +  transition-property: border-color, background, color, transform, box-shadow;
transition에 영향을 받는 내용들을 먼저 보여주고 밑에 transition에 대한 정보를 적어주는게 정보의 흐름을 따라가기 쉽지 않을까 생각해서 그랬습니다.

2021-12-08 14:12 UTC, KimChunsick commented on packages/core/src/components/Button/Button.tsx
> +    <Element type='submit' disabled={disabled || loading} {...otherProps} onClick={onClick}>
vercel 에서 그렇게 했길래 그랬습니다... 수정하겠습니다.

2021-12-08 14:13 UTC, KimChunsick commented on packages/core/src/components/Button/Button.tsx
> +    border: 1px solid ${props.normal?.border};
해당 부분을 실수로 놓치고 커밋했네요. 수정하겠습니다.

2021-12-08 14:13 UTC, KimChunsick commented on packages/core/src/components/Button/Button.tsx
> +    color: ${props.normal?.foreground};
해당 부분을 실수로 놓치고 커밋했네요. 수정하겠습니다.

2021-12-08 14:21 UTC, KimChunsick commented on packages/core/src/components/Button/Button.tsx
> +    margin-right: ${props.align === 'grow' || props.align === 'start' ? 'auto' : undefined};
허허.. 죄송함다..

2021-12-08 14:21 UTC, KimChunsick commented on packages/core/src/components/Button/Button.tsx
> +    margin-right: ${props.isPrefix ? '8px' : undefined};
허허.. 죄송함다..

2021-12-08 14:21 UTC, KimChunsick commented on packages/core/src/components/Button/Button.tsx
> +      width: ${props.width ? `${props.width}px` : undefined};
허허.. 죄송함다..

2021-12-08 17:39 UTC, Vallista commented on packages/core/src/components/Button/useButton.ts
> +  const color = props.color || 'primary'
|| -> ??

2021-12-08 17:41 UTC, Vallista requested changes
^^

2021-12-08 17:41 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +        background-image: linear-gradient(to right, hsla(0, 0%, 100%, 0.8), hsla(0, 0%, 100%, 0.8));
^^

2021-12-08 17:41 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +        background-image: linear-gradient(to right, hsla(0, 0%, 100%, 0.7), hsla(0, 0%, 100%, 0.7));
^^

2021-12-08 17:41 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +      background-image: linear-gradient(to right, hsla(0, 0%, 100%, 0.8), hsla(0, 0%, 100%, 0.8));
^^

2021-12-08 17:41 UTC, Vallista commented on packages/core/src/components/Button/Button.tsx
> +// export const Button: FC<Partial<ButtonProps> & Partial<Pick<ButtonProps, 'normal' | 'hover' | 'active'>>> = (props) => {
주석

2021-12-08 17:52 UTC, Vallista approved these changes
ㅇㅋ

2021-12-08 17:53 UTC, merged