feat: Icon 컴포넌트 완료 (아이콘추가는 약 1/3 완료)
Vallista/vallista-land pull request #4
Opened 2021-12-13 15:55 UTC by KimChunsick

Signed-off-by: deokwon <deokwon@deokwonui-MacBookPro.local>

2021-12-13 16:02 UTC, Vallista requested changes

2021-12-13 16:02 UTC, Vallista commented on packages/core/src/components/Icon/Activity/index.tsx
> +      width={size ?? 24}
전반적으로 중복되는데, useIcon 같은걸로 빼서 size를 별도로 가져오면 좋을듯요.

2021-12-13 16:02 UTC, Vallista commented on packages/core/src/components/Icon/Activity/index.tsx
> +      width={size ?? 24}
아니면 위에서 size = 24

2021-12-13 16:02 UTC, Vallista commented on packages/core/src/components/Icon/Activity/index.tsx
> +      stroke={color ?? theme.colors.PRIMARY.FOREGROUND}
color 도 

color = theme.colors.PRIMARY.FOREGROUND 했으면 될 듯

2021-12-13 16:02 UTC, Vallista commented on packages/blog/src/pages/IconPlayground/index.tsx
> +import { Container, Activity } from 'core'
Activity 형태가 아니라, Modal 처럼

Icon.Activity 이렇게 하는게 맞을듯요.

2021-12-13 16:02 UTC, Vallista commented on packages/blog/src/pages/IconPlayground/index.tsx
> +import { Container, Activity } from 'core'
이렇게하면 중복되는거 많을듯

2021-12-14 17:55 UTC, Vallista commented on packages/core/src/components/index.ts
> +export * from './Icon'
왜 두개..?

2021-12-14 17:56 UTC, Vallista commented on packages/core/src/components/Icon/index.tsx
> +export * from './assets'
./assets 를 Icon으로 설정했는데, 이게 또 필요?

2021-12-14 17:57 UTC, Vallista approved these changes
리뷰 두 개 고치고 머지하면 됨

2021-12-14 17:59 UTC, KimChunsick commented on packages/core/src/components/Icon/index.tsx
> +export * from './assets'
아이콘을 따로 하나만 접근할 수 있게하는 방법도 필요하지 않을까 싶어 추가 했습니다.
<Icon.Bell />과 <Bell />을 모두 사용할 수 있게요.

2021-12-14 18:00 UTC, KimChunsick commented on packages/core/src/components/index.ts
> +export * from './Icon'
rebase 과정에서 실수 한 것 같습니다. 지금 수정해서 올리도록 하겠습니다.

2021-12-14 18:00 UTC, Vallista commented on packages/core/src/components/Icon/index.tsx
> +export * from './assets'
ㄴㄴ .Icon.Bell 만 하셈. 
Icon으로 래핑한 이유는 이름이 중복될 가능성이 있기 때문에 래핑한 것

2021-12-14 18:02 UTC, KimChunsick commented on packages/core/src/components/Icon/index.tsx
> +export * from './assets'
추후 이름이 겹칠 수 있겠네요 수정하겠습니다

2021-12-14 18:06 UTC, merged